### ISSUE TITLE
FR: Per domain rules

### ISSUE THREAD

**Issue by ivucica** [Rufflewind/chrome_script#2]
I like the simplicity of the extension, but it might still make sense for the extension to offer per-domain rules. Some elements that I'd like to override on certain domains are overly broad to be applied everywhere.

What do you think?

**Comment by Rufflewind** [comment]
From the comment on 2017-01-10:

> You can make it site-specific using JS in conjunction with a custom CSS class as demonstrated in the example: https://github.com/Rufflewind/chrome_script/tree/master/example
>
> I would prefer to keep the extension as simple as possible.

To elaborate, copy the `addCustomClassToHtml` function from https://github.com/Rufflewind/chrome_script/blob/master/example/example.js. Call that function to set a custom `class="..."` on the `<html>` element depending on the URL:

```js
addCustomClassToHtml([
    [/https:\/\/mail\.google\.com\//, "cs-gmail"],   // Example: Gmail will have <html class="cs-gmail ...">
]);
```

Then in the CSS rules you can do something like https://github.com/Rufflewind/chrome_script/blob/master/example/example.css:

```js
// Make all text on Gmail red.
.cs-gmail div {
    color: red;
}
```
